# Generated by Django 4.0.4 on 2022-08-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_type_identifier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='deleted',
            field=models.BooleanField(default=1),
        ),
    ]
