# Generated by Django 4.0.4 on 2022-08-11 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
