# Generated by Django 4.0.4 on 2022-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_identifier_deleted_alter_identifier_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
