# Generated by Django 4.0.4 on 2022-08-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_type_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='warehouse',
            field=models.CharField(choices=[('raw', 'Xom ashyo'), ('ready_prod', 'Tayyor maxsulot')], default='raw', max_length=20),
        ),
    ]
